package datn.datn_expansemanagement.screen.add_expense_loan.prsentation

import datn.datn_expansemanagement.core.base.domain.provider.AndroidResourceProvider

class AddExpenseLoanResource: AndroidResourceProvider()