package datn.datn_expansemanagement.screen.add_expense_donate.presentation

import datn.datn_expansemanagement.core.base.domain.provider.AndroidResourceProvider

class AddExpenseDonateResource : AndroidResourceProvider()